# Generated by Django 2.2.4 on 2019-08-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('date_discharged', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('bed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed.Bed')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='BaselineRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=50)),
                ('pulse_rate', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('respiratory_rate', models.CharField(max_length=50)),
                ('oxygen_circulation', models.CharField(max_length=50)),
                ('date_collected', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
